"""
Generic Session Manager (slim)

A minimal in-process registry of active orchestrator sessions. The LangGraph
checkpointer owns all per-session data; this module only tracks which
session IDs are currently live so the application can:

- report an "active sessions" count from /health,
- evict stale sessions after a TTL (so the checkpointer's memory does not
  grow without bound), and
- inject a different registry in tests.

This module replaces the older ``GenericSessionManager`` which mirrored CV /
job / message state on top of the (now-deleted) Writer chat endpoints. After
the orchestrator migration that mirroring is dead weight: every node update
is checkpointed by LangGraph against ``thread_id == session_id``.
"""

from __future__ import annotations

import threading
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Optional


def _now() -> datetime:
    """Timezone-aware UTC 'now'. Centralized so we can swap clocks in tests."""
    return datetime.now(timezone.utc)


@dataclass
class _SessionRecord:
    """One row of the registry."""
    session_id: str
    flow: str
    created_at: datetime = field(default_factory=_now)
    last_accessed: datetime = field(default_factory=_now)


class GenericSessionManager:
    """In-process registry of active orchestrator sessions.

    ``session_id`` doubles as the LangGraph ``thread_id`` - they are the same
    UUID generated by the orchestrator router on /start.
    """

    def __init__(self, ttl_minutes: int = 60) -> None:
        self.ttl = timedelta(minutes=ttl_minutes)
        self.ttl_minutes = ttl_minutes
        self._records: dict[str, _SessionRecord] = {}
        self._lock = threading.Lock()

    # ----- registry operations ---------------------------------------------

    def register(self, session_id: str, flow: str) -> None:
        """Record a newly-created orchestrator session."""
        with self._lock:
            self._records[session_id] = _SessionRecord(
                session_id=session_id,
                flow=flow,
            )

    def touch(self, session_id: str) -> bool:
        """Update last_accessed on every /message call. Returns False if unknown."""
        with self._lock:
            record = self._records.get(session_id)
            if record is None:
                return False
            record.last_accessed = _now()
            return True

    def exists(self, session_id: str) -> bool:
        with self._lock:
            return session_id in self._records

    def delete(self, session_id: str) -> bool:
        with self._lock:
            return self._records.pop(session_id, None) is not None

    def get_session_count(self) -> int:
        """Public accessor used by /health."""
        with self._lock:
            return len(self._records)

    def cleanup_expired_sessions(self) -> int:
        """Drop entries that have not been accessed within the TTL.

        Returns the number of sessions evicted. Intended for periodic
        background invocation; calling it inline from a request handler is
        also safe because the operation is O(n) and uses a single lock.
        """
        cutoff = _now() - self.ttl
        with self._lock:
            expired = [
                sid for sid, rec in self._records.items() if rec.last_accessed < cutoff
            ]
            for sid in expired:
                del self._records[sid]
        return len(expired)


# --------------------------------------------------------------------------- #
# Module-level singleton with thread-safe lazy init.
# --------------------------------------------------------------------------- #

_session_manager: Optional[GenericSessionManager] = None
_session_manager_lock = threading.Lock()


def get_session_manager() -> GenericSessionManager:
    """Get the global session-registry instance."""
    global _session_manager
    if _session_manager is None:
        with _session_manager_lock:
            if _session_manager is None:
                _session_manager = GenericSessionManager(ttl_minutes=60)
    return _session_manager


def reset_session_manager() -> None:
    """Reset the registry. Useful for tests."""
    global _session_manager
    with _session_manager_lock:
        _session_manager = None
